### ISSUE TITLE
Receiving "error in the configuration: both spec and arguments provided: configuration error"

### ISSUE THREAD

**Issue by joe-elliott** [drone-plugins/drone-manifest#41]
So this seems to be related to this change:

https://github.com/drone-plugins/drone-manifest/pull/40

Our configuration looks like:

```
- image: plugins/manifest
  name: manifest-tempo
  settings:
    password:
      from_secret: docker_password
    spec: .drone/docker-manifest.tmpl
    target: tempo
    username:
      from_secret: docker_username
```

and our template looks like:

```

image: grafana/{{config.target}}
tags:
  - latest
  - {{build.tags}}
manifests:
  - image: grafana/{{config.target}}:{{build.tags}}-amd64
    platform:
      architecture: amd64
      os: linux
  - image: grafana/{{config.target}}:{{build.tags}}-arm64
    platform:
      architecture: arm64
      os: linux
```

in particular this condition is causing issues:

https://github.com/drone-plugins/drone-manifest/blob/af5721dace68ce1cacae7fccdf948efda66da35a/plugin/plugin.go#L167

is it intentional that we can't provide a target and a template? note that we use the target in our template. is there a better way to do that?
